# Generated by Django 3.2.25 on 2024-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
