# Generated by Django 3.2.25 on 2024-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240330_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
